@extends('layout')
@section('content')
<a href="/">← Căutare</a><h1>{{ $offer->title }}</h1><p>{{ config('scanner.sources.'.$offer->source.'.name',$offer->source) }} · {{ $offer->seller }}</p>
@if($offer->product)<p><a class="button" href="/products/{{ $offer->product->id }}">Analiza produsului canonic →</a></p>@endif
@if($offer->access_method==='local_file')<div class="notice">Ofertă importată din fișier local. Data indică importul, nu o verificare online la magazin.</div>@endif
<div class="grid"><div class="card"><h3>Preț produs actual</h3><div class="price">{{ number_format($offer->price/100,2,',','.') }} {{ $offer->currency }}</div><p>Total: {{ $offer->total===null?'necunoscut (livrare neprecizată)':number_format($offer->total/100,2,',','.').' '.$offer->currency }}</p></div><div class="card"><h3>Minim istoric produs</h3><div class="price">{{ number_format(($points->min('price')??$offer->price)/100,2,',','.') }} {{ $offer->currency }}</div></div><div class="card"><h3>Maxim istoric produs</h3><div class="price">{{ number_format(($points->max('price')??$offer->price)/100,2,',','.') }} {{ $offer->currency }}</div></div></div>
<p>EAN: {{ $offer->ean??'—' }} · Model: {{ $offer->model??'—' }} · SKU: {{ $offer->sku??'—' }}</p><p>Verificat: {{ $offer->checked_at->format('d.m.Y H:i') }} · Disponibilitate: {{ $offer->availability }}</p><a class="button" href="{{ $offer->url }}" target="_blank" rel="noopener noreferrer">Vezi oferta la magazin ↗</a>
@auth
@if($offer->productMatch && $offer->productMatch->review_status==='pending')<div class="card admin"><h2>Matching necesită verificare</h2><p>Propunere: <a href="/products/{{ $offer->productMatch->canonical_product_id }}">{{ $offer->productMatch->product?->name }}</a> · {{ $offer->productMatch->classification }} · {{ $offer->productMatch->confidence }}%</p><p><small>{{ json_encode($offer->productMatch->signals, JSON_UNESCAPED_UNICODE) }}</small></p><form method="post" action="/matches/{{ $offer->productMatch->id }}/review">@csrf<textarea name="note" maxlength="1000" placeholder="Notă opțională"></textarea><button name="decision" value="approved">Confirmă asocierea</button><button class="danger" name="decision" value="rejected">Respinge</button></form></div>@endif
@if(!$offer->canonical_product_id)<details class="card"><summary>Creează produs canonic din această ofertă</summary><form method="post" action="/offers/{{ $offer->id }}/canonical-product">@csrf<label>Denumire canonică<input name="name" value="{{ $offer->title }}" required maxlength="255"></label><label>Brand<input name="brand" value="{{ $offer->brand }}"></label><label>Producător<input name="manufacturer"></label><label>Model<input name="model" value="{{ $offer->model }}"></label><label>MPN<input name="mpn" value="{{ $offer->mpn }}"></label><label>Categorie<input name="category"></label><label>Aliasuri, câte unul pe linie<textarea name="aliases"></textarea></label><button>Creează și leagă oferta</button></form></details>@endif
<div class="card admin"><h2>Urmărește costul total</h2><form method="post" action="/offers/{{ $offer->id }}/watch">@csrf<label for="threshold">Anunță-mă când totalul scade sub</label><input id="threshold" name="threshold" inputmode="decimal" value="{{ $offer->watch?number_format($offer->watch->threshold/100,2,'.',''):'' }}" placeholder="500.00" required><button>Salvează pragul</button></form></div>
@endauth
<div class="card"><h2>Evoluția prețului produsului</h2><p class="muted">Fără livrare. Se salvează un punct doar când prețul, livrarea sau disponibilitatea se schimbă.</p>
@if($points->count()>1)
@php
 $min=$points->min('price');$max=$points->max('price');$start=$points->first()->observed_at->timestamp;$span=max(1,$points->last()->observed_at->timestamp-$start);$coords=[];
 foreach($points as $p){$coords[]=(20+760*($p->observed_at->timestamp-$start)/$span).','.(180-150*($p->price-$min)/max(1,$max-$min));}
@endphp
<svg viewBox="0 0 800 210" role="img" aria-label="Evoluție preț produs; valorile și datele exacte sunt în tabelul de mai jos"><line x1="20" y1="185" x2="780" y2="185" stroke="#ccd9d0"/><polyline points="{{ implode(' ',$coords) }}" fill="none" stroke="#166953" stroke-width="3"/></svg>
@else<p>Graficul va apărea după cel puțin două observații diferite.</p>@endif
<div class="table"><table><thead><tr><th>Data schimbării</th><th>Preț produs</th><th>Livrare</th><th>Disponibilitate</th></tr></thead><tbody>@foreach($points as $p)<tr><td>{{ $p->observed_at->format('d.m.Y H:i:s') }}</td><td>{{ number_format($p->price/100,2,',','.') }} lei</td><td>{{ $p->shipping===null?'Necunoscută':number_format($p->shipping/100,2,',','.').' lei' }}</td><td>{{ $p->availability }}</td></tr>@endforeach</tbody></table></div></div>
@endsection
