@extends('layout')
@section('content')
<span class="badge">COMPARĂ CU ÎNCREDERE</span><h1>Același produs. Prețuri la vedere.</h1><p class="muted">Caută după denumire, model sau EAN. Vezi clar ce este confirmat și ce este doar similar.</p>
<form class="card" method="get" action="/"><label for="q">Ce produs cauți?</label><div class="search"><input id="q" name="q" maxlength="200" value="{{ session('ocr_text',$q) }}" placeholder="Denumire, model, cod EAN / GTIN" required><button>Caută în ofertele salvate</button></div><p class="muted">Căutarea folosește catalogul local. „Actualizează sursele” solicită verificarea feedurilor aprobate.</p></form>
<div class="row"><h2>Surse de preț</h2><form action="/sync" method="post">@csrf<button>Actualizează sursele</button></form><a href="/export">Export CSV</a></div>
<div class="grid">@foreach(config('scanner.sources') as $key=>$source) @php($state=$states->get($key))<div class="card"><h3>{{ $source['name'] }}</h3><span class="badge {{ ($state->status??'')==='ok'?'good':'' }}">{{ ['ok'=>'Verificat','error'=>'Eroare','running'=>'În lucru','disabled'=>'Neactivat'][$state->status??'disabled'] }}</span><p>{{ $state->message??'Necesită acces aprobat la feed. Nu sunt afișate date inventate.' }}</p>@if(!$source['approved'] && isset($source['requires']))<small>Acces necesar: {{ $source['requires'] }}</small><br>@endif<small>Ultima verificare reușită: {{ $state->last_success??'—' }}</small></div>@endforeach</div>
@if($q!=='')<section class="card"><h2>{{ $count }} rezultate pentru „{{ $q }}”</h2><p class="muted">Maximum 100 afișate. Totalurile cunoscute sunt ordonate crescător în fiecare categorie. Livrarea necunoscută împiedică o comparație completă.</p>
@if(collect($results)->contains(fn($r)=>$r['offer']->access_method==='local_file'))<div class="notice">Rezultatele includ fișiere importate local. Consultă proveniența în pagina ofertei; importul nu este verificare online.</div>@endif
@if($minimum!==null)<div class="notice">Cel mai mic total confirmat în ofertele disponibile și verificate în ultimele 24h: <strong>{{ number_format($minimum/100,2,',','.') }} lei</strong>. Ofertele fără livrare cunoscută sunt excluse.</div>@endif
@if(!$count)<p>Nu există oferte potrivite în catalog. Verifică activarea surselor sau încearcă alt identificator.</p>@else<div class="table"><table><thead><tr><th>Produs / potrivire</th><th>Magazin / seller</th><th>Preț</th><th>Livrare</th><th>Total</th><th>Stare / verificare</th></tr></thead><tbody>
@foreach($results as $r)@php($o=$r['offer'])<tr><td><a href="/offers/{{ $o->id }}"><strong>{{ $o->title }}</strong></a><p><span class="badge {{ $r['match']['kind']==='exact'?'good':'' }}">{{ $r['match']['kind']==='exact'?'Același GTIN':'Similar · '.$r['match']['score'].'% termeni' }}</span></p><small>{{ $r['match']['reason'] }}</small></td><td>{{ config('scanner.sources.'.$o->source.'.name',$o->source) }}<br>{{ $o->seller }}</td><td>{{ number_format($o->price/100,2,',','.') }}</td><td>{{ $o->shipping===null?'Necunoscută':number_format($o->shipping/100,2,',','.') }}</td><td><strong>{{ $o->total===null?'Necunoscut':number_format($o->total/100,2,',','.').' lei' }}</strong>@if($minimum!==null && $r['match']['kind']==='exact' && $o->total!==null && $o->availability==='in_stock' && $o->checked_at->gt(now()->subHours(24)))<p class="badge good">{{ $o->total===$minimum?'Cel mai mic total':'+'.number_format(($o->total-$minimum)/100,2,',','.').' lei' }}</p>@endif</td><td>{{ ['in_stock'=>'În stoc','out_of_stock'=>'Fără stoc','preorder'=>'Precomandă','unknown'=>'Necunoscută'][$o->availability] }}<br><small>{{ $o->checked_at->format('d.m.Y H:i') }}</small>@if($o->checked_at->lt(now()->subHours(24)))<p class="badge">Date vechi</p>@endif</td></tr>@endforeach
</tbody></table></div>@endif</section>@endif
<div class="card"><h2>Produse urmărite</h2>@forelse($watches as $watch)<div class="row"><a href="/offers/{{ $watch->offer_id }}">{{ $watch->offer->title }} · sub {{ number_format($watch->threshold/100,2,',','.') }} lei</a><form action="/watches/{{ $watch->id }}" method="post">@csrf @method('DELETE')<button class="danger">Oprește</button></form></div>@empty<p class="muted">Deschide o ofertă și stabilește pragul pentru costul total.</p>@endforelse</div>
<div class="card"><h2>Alerte interne</h2>@forelse($alerts as $alert)<p>{{ $alert->title }} · <strong>{{ number_format($alert->total/100,2,',','.') }} lei</strong> · {{ $alert->created_at }}</p>@if(!$alert->read_at)<form action="/alerts/{{ $alert->id }}/read" method="post">@csrf<button>Marchează citită</button></form>@endif @empty<p class="muted">Nicio alertă. Notificăm o singură dată la trecerea sub prag, doar pentru total cunoscut și produs în stoc.</p>@endforelse</div>
<details class="card"><summary>Identificare din fotografie · infrastructură OCR locală</summary><p>Încarcă eticheta produsului. Dacă OCR local este configurat, poți corecta textul extras și căuta cu motorul existent. Recunoașterea vizuală și căutarea după asemănare nu sunt încă disponibile.</p><form action="/image" method="post" enctype="multipart/form-data">@csrf<label for="image">JPG, PNG sau WebP · maximum 5 MB</label><input type="file" id="image" name="image" accept="image/jpeg,image/png,image/webp" required><button>Citește eticheta</button></form></details>
@endsection
